In [ ]:
# **지시사항:**

# 1. 다음 벡터를 생성하고 내적 계산
#    - v1 = [1, 2, 3, 4], v2 = [5, 6, 7, 8]
#    - np.dot() 또는 @ 연산자 사용
#    - 결과 출력 및 수동 검증

# 2. 행렬 곱셈 수행
#    - 2×3 행렬 A와 3×2 행렬 B 생성
#    - A @ B 계산 (결과: 2×2 행렬)

# 3. 벡터 노름 계산
#    - 벡터 c = [3, 4, 5]에 대해
#    - L1, L2, L∞ 노름 모두 계산
#    - np.linalg.norm() 사용

# 4. 조건부 인덱싱
#    - 배열 data = [1, 5, 3, 8, 2, 9, 4, 7, 6]
#    - 5보다 큰 값 추출
#    - 3 이상 7 이하 값 추출
#    - 짝수 값 추출

# **필수 라이브러리:**
# pip install numpy
# ```

In [7]:
import numpy as np  
import pandas as pd 

In [14]:
v1 = [1, 2, 3, 4]
v1 = np.array(v1)
v2 = [5, 6, 7, 8]
v2 = np.array(v2)
np.dot(v1,v2)

np.int64(70)

In [15]:
result = v1 @ v2
result

np.int64(70)

In [23]:
v1 = np.random.rand(2,3)
v2 = np.random.rand(3,2)
v1, v2

(array([[0.00467257, 0.19382657, 0.37986565],
        [0.83554202, 0.83645541, 0.68481449]]),
 array([[0.22363978, 0.12955099],
        [0.98771801, 0.08669844],
        [0.14595094, 0.91016233]]))

In [24]:
result = v1 @ v2
result

array([[0.24793272, 0.3631492 ],
       [1.11299182, 0.80405703]])

In [26]:
c = [3, 4, 5]
c = np.array(c)
np.linalg.norm(c)

np.float64(7.0710678118654755)

In [33]:
data = [1, 5, 3, 8, 2, 9, 4, 7, 6]
data = np.array(data)


In [30]:
data2 = data[data > 5]
data2

array([8, 9, 7, 6])

In [35]:
data2 = data[(data > 3) & (data <7)]
data2

array([5, 4, 6])